/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hindi' : IDL.Null,
  'malayalam' : IDL.Null,
  'kannada' : IDL.Null,
  'telugu' : IDL.Null,
});
export const MovieGenre = IDL.Variant({
  'action' : IDL.Null,
  'thriller' : IDL.Null,
  'comedy' : IDL.Null,
  'horror' : IDL.Null,
  'devotional' : IDL.Null,
  'drama' : IDL.Null,
  'romance' : IDL.Null,
  'family' : IDL.Null,
});
export const SongGenre = IDL.Variant({
  'pop' : IDL.Null,
  'tamil' : IDL.Null,
  'carnatic' : IDL.Null,
  'bollywood' : IDL.Null,
  'folk' : IDL.Null,
  'rock' : IDL.Null,
  'malayalam' : IDL.Null,
  'telugu' : IDL.Null,
  'devotional' : IDL.Null,
  'classical' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const City = IDL.Variant({
  'chennai' : IDL.Null,
  'kerala' : IDL.Null,
  'hyderabad' : IDL.Null,
  'tamilNadu' : IDL.Null,
  'bangalore' : IDL.Null,
  'kochi' : IDL.Null,
});
export const Category = IDL.Variant({
  'collegeEvent' : IDL.Null,
  'businessMeeting' : IDL.Null,
  'celebrityChiefGuest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'chiefGuestName' : IDL.Opt(IDL.Text),
  'venue' : IDL.Text,
  'city' : City,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'organizerName' : IDL.Text,
  'category' : Category,
  'rewardEarned' : IDL.Nat,
});
export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'cast' : IDL.Text,
  'description' : IDL.Text,
  'director' : IDL.Text,
  'language' : Language,
  'genre' : MovieGenre,
  'rating' : IDL.Nat,
  'releaseYear' : IDL.Nat,
});
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'language' : IDL.Text,
  'genre' : SongGenre,
  'artist' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'eventsPosted' : IDL.Vec(IDL.Nat),
  'rewardBalance' : IDL.Nat,
});
export const BookingRecord = IDL.Record({
  'eventId' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'attendeeName' : IDL.Text,
  'booker' : IDL.Principal,
  'bookingDate' : IDL.Text,
  'phone' : IDL.Text,
  'numberOfSeats' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMovie' : IDL.Func(
      [
        IDL.Text,
        Language,
        MovieGenre,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'addSong' : IDL.Func(
      [IDL.Text, IDL.Text, SongGenre, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        City,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getBookingCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventBookings' : IDL.Func([IDL.Nat], [IDL.Vec(BookingRecord)], ['query']),
  'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEventRegistrations' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getEventsByCategory' : IDL.Func([Category], [IDL.Vec(Event)], ['query']),
  'getEventsByCity' : IDL.Func([City], [IDL.Vec(Event)], ['query']),
  'getMoviesByGenre' : IDL.Func([MovieGenre], [IDL.Vec(Movie)], ['query']),
  'getMoviesByLanguage' : IDL.Func([Language], [IDL.Vec(Movie)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRecord)], ['query']),
  'getSongsByGenre' : IDL.Func([SongGenre], [IDL.Vec(Song)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserRegistered' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForEvent' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hindi' : IDL.Null,
    'malayalam' : IDL.Null,
    'kannada' : IDL.Null,
    'telugu' : IDL.Null,
  });
  const MovieGenre = IDL.Variant({
    'action' : IDL.Null,
    'thriller' : IDL.Null,
    'comedy' : IDL.Null,
    'horror' : IDL.Null,
    'devotional' : IDL.Null,
    'drama' : IDL.Null,
    'romance' : IDL.Null,
    'family' : IDL.Null,
  });
  const SongGenre = IDL.Variant({
    'pop' : IDL.Null,
    'tamil' : IDL.Null,
    'carnatic' : IDL.Null,
    'bollywood' : IDL.Null,
    'folk' : IDL.Null,
    'rock' : IDL.Null,
    'malayalam' : IDL.Null,
    'telugu' : IDL.Null,
    'devotional' : IDL.Null,
    'classical' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const City = IDL.Variant({
    'chennai' : IDL.Null,
    'kerala' : IDL.Null,
    'hyderabad' : IDL.Null,
    'tamilNadu' : IDL.Null,
    'bangalore' : IDL.Null,
    'kochi' : IDL.Null,
  });
  const Category = IDL.Variant({
    'collegeEvent' : IDL.Null,
    'businessMeeting' : IDL.Null,
    'celebrityChiefGuest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'chiefGuestName' : IDL.Opt(IDL.Text),
    'venue' : IDL.Text,
    'city' : City,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'organizerName' : IDL.Text,
    'category' : Category,
    'rewardEarned' : IDL.Nat,
  });
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'cast' : IDL.Text,
    'description' : IDL.Text,
    'director' : IDL.Text,
    'language' : Language,
    'genre' : MovieGenre,
    'rating' : IDL.Nat,
    'releaseYear' : IDL.Nat,
  });
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'language' : IDL.Text,
    'genre' : SongGenre,
    'artist' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'eventsPosted' : IDL.Vec(IDL.Nat),
    'rewardBalance' : IDL.Nat,
  });
  const BookingRecord = IDL.Record({
    'eventId' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'attendeeName' : IDL.Text,
    'booker' : IDL.Principal,
    'bookingDate' : IDL.Text,
    'phone' : IDL.Text,
    'numberOfSeats' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMovie' : IDL.Func(
        [
          IDL.Text,
          Language,
          MovieGenre,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'addSong' : IDL.Func(
        [IDL.Text, IDL.Text, SongGenre, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          City,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getBookingCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventBookings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEventRegistrations' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getEventsByCategory' : IDL.Func([Category], [IDL.Vec(Event)], ['query']),
    'getEventsByCity' : IDL.Func([City], [IDL.Vec(Event)], ['query']),
    'getMoviesByGenre' : IDL.Func([MovieGenre], [IDL.Vec(Movie)], ['query']),
    'getMoviesByLanguage' : IDL.Func([Language], [IDL.Vec(Movie)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRecord)], ['query']),
    'getSongsByGenre' : IDL.Func([SongGenre], [IDL.Vec(Song)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserRegistered' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForEvent' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };