/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRecord {
  'eventId' : bigint,
  'bookingId' : bigint,
  'attendeeName' : string,
  'booker' : Principal,
  'bookingDate' : string,
  'phone' : string,
  'numberOfSeats' : bigint,
}
export type Category = { 'collegeEvent' : null } |
  { 'businessMeeting' : null } |
  { 'celebrityChiefGuest' : null };
export type City = { 'chennai' : null } |
  { 'kerala' : null } |
  { 'hyderabad' : null } |
  { 'tamilNadu' : null } |
  { 'bangalore' : null } |
  { 'kochi' : null };
export interface Event {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'chiefGuestName' : [] | [string],
  'venue' : string,
  'city' : City,
  'date' : string,
  'description' : string,
  'organizerName' : string,
  'category' : Category,
  'rewardEarned' : bigint,
}
export type Language = { 'tamil' : null } |
  { 'hindi' : null } |
  { 'malayalam' : null } |
  { 'kannada' : null } |
  { 'telugu' : null };
export interface Movie {
  'id' : bigint,
  'title' : string,
  'cast' : string,
  'description' : string,
  'director' : string,
  'language' : Language,
  'genre' : MovieGenre,
  'rating' : bigint,
  'releaseYear' : bigint,
}
export type MovieGenre = { 'action' : null } |
  { 'thriller' : null } |
  { 'comedy' : null } |
  { 'horror' : null } |
  { 'devotional' : null } |
  { 'drama' : null } |
  { 'romance' : null } |
  { 'family' : null };
export interface Song {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'language' : string,
  'genre' : SongGenre,
  'artist' : string,
}
export type SongGenre = { 'pop' : null } |
  { 'tamil' : null } |
  { 'carnatic' : null } |
  { 'bollywood' : null } |
  { 'folk' : null } |
  { 'rock' : null } |
  { 'malayalam' : null } |
  { 'telugu' : null } |
  { 'devotional' : null } |
  { 'classical' : null };
export interface UserProfile {
  'username' : string,
  'eventsPosted' : Array<bigint>,
  'rewardBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMovie' : ActorMethod<
    [string, Language, MovieGenre, bigint, string, string, string, bigint],
    undefined
  >,
  'addSong' : ActorMethod<
    [string, string, SongGenre, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookEvent' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'createEvent' : ActorMethod<
    [string, string, City, Category, string, string, string, [] | [string]],
    undefined
  >,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllMovies' : ActorMethod<[], Array<Movie>>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getBookingCount' : ActorMethod<[bigint], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventBookings' : ActorMethod<[bigint], Array<BookingRecord>>,
  'getEventById' : ActorMethod<[bigint], Event>,
  'getEventRegistrations' : ActorMethod<[bigint], bigint>,
  'getEventsByCategory' : ActorMethod<[Category], Array<Event>>,
  'getEventsByCity' : ActorMethod<[City], Array<Event>>,
  'getMoviesByGenre' : ActorMethod<[MovieGenre], Array<Movie>>,
  'getMoviesByLanguage' : ActorMethod<[Language], Array<Movie>>,
  'getMyBookings' : ActorMethod<[], Array<BookingRecord>>,
  'getSongsByGenre' : ActorMethod<[SongGenre], Array<Song>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserRegistered' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForEvent' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'searchMovies' : ActorMethod<[string], Array<Movie>>,
  'searchSongs' : ActorMethod<[string], Array<Song>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];