/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookingRecord {
    eventId: bigint;
    bookingId: bigint;
    attendeeName: string;
    booker: Principal;
    bookingDate: string;
    phone: string;
    numberOfSeats: bigint;
}
export interface Movie {
    id: bigint;
    title: string;
    cast: string;
    description: string;
    director: string;
    language: Language;
    genre: MovieGenre;
    rating: bigint;
    releaseYear: bigint;
}
export interface Song {
    id: bigint;
    title: string;
    duration: string;
    language: string;
    genre: SongGenre;
    artist: string;
}
export interface Event {
    id: bigint;
    title: string;
    creator: Principal;
    chiefGuestName?: string;
    venue: string;
    city: City;
    date: string;
    description: string;
    organizerName: string;
    category: Category;
    rewardEarned: bigint;
}
export interface UserProfile {
    username: string;
    eventsPosted: Array<bigint>;
    rewardBalance: bigint;
}
export enum Category {
    collegeEvent = "collegeEvent",
    businessMeeting = "businessMeeting",
    celebrityChiefGuest = "celebrityChiefGuest"
}
export enum City {
    chennai = "chennai",
    kerala = "kerala",
    hyderabad = "hyderabad",
    tamilNadu = "tamilNadu",
    bangalore = "bangalore",
    kochi = "kochi"
}
export enum Language {
    tamil = "tamil",
    hindi = "hindi",
    malayalam = "malayalam",
    kannada = "kannada",
    telugu = "telugu"
}
export enum MovieGenre {
    action = "action",
    thriller = "thriller",
    comedy = "comedy",
    horror = "horror",
    devotional = "devotional",
    drama = "drama",
    romance = "romance",
    family = "family"
}
export enum SongGenre {
    pop = "pop",
    tamil = "tamil",
    carnatic = "carnatic",
    bollywood = "bollywood",
    folk = "folk",
    rock = "rock",
    malayalam = "malayalam",
    telugu = "telugu",
    devotional = "devotional",
    classical = "classical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMovie(title: string, language: Language, genre: MovieGenre, releaseYear: bigint, director: string, cast: string, description: string, rating: bigint): Promise<void>;
    addSong(title: string, artist: string, genre: SongGenre, language: string, duration: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookEvent(eventId: bigint, attendeeName: string, phone: string, numberOfSeats: bigint, bookingDate: string): Promise<void>;
    createEvent(title: string, description: string, city: City, category: Category, date: string, venue: string, organizerName: string, chiefGuestName: string | null): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAllMovies(): Promise<Array<Movie>>;
    getAllSongs(): Promise<Array<Song>>;
    getBookingCount(eventId: bigint): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEventBookings(eventId: bigint): Promise<Array<BookingRecord>>;
    getEventById(id: bigint): Promise<Event>;
    getEventRegistrations(eventId: bigint): Promise<bigint>;
    getEventsByCategory(category: Category): Promise<Array<Event>>;
    getEventsByCity(city: City): Promise<Array<Event>>;
    getMoviesByGenre(genre: MovieGenre): Promise<Array<Movie>>;
    getMoviesByLanguage(language: Language): Promise<Array<Movie>>;
    getMyBookings(): Promise<Array<BookingRecord>>;
    getSongsByGenre(genre: SongGenre): Promise<Array<Song>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserRegistered(eventId: bigint): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    registerForEvent(eventId: bigint): Promise<void>;
    saveCallerUserProfile(username: string): Promise<void>;
    searchMovies(searchTerm: string): Promise<Array<Movie>>;
    searchSongs(searchTerm: string): Promise<Array<Song>>;
}
import type { Category as _Category, City as _City, Event as _Event, Language as _Language, Movie as _Movie, MovieGenre as _MovieGenre, Song as _Song, SongGenre as _SongGenre, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMovie(arg0: string, arg1: Language, arg2: MovieGenre, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMovie(arg0, to_candid_Language_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MovieGenre_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMovie(arg0, to_candid_Language_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MovieGenre_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addSong(arg0: string, arg1: string, arg2: SongGenre, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSong(arg0, arg1, to_candid_SongGenre_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSong(arg0, arg1, to_candid_SongGenre_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookEvent(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: City, arg3: Category, arg4: string, arg5: string, arg6: string, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, to_candid_City_n9(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, to_candid_City_n9(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMovies(): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMovies();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMovies();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSongs(): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingCount(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventBookings(arg0: bigint): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventBookings(arg0);
            return result;
        }
    }
    async getEventById(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventRegistrations(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventRegistrations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventRegistrations(arg0);
            return result;
        }
    }
    async getEventsByCategory(arg0: Category): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByCategory(to_candid_Category_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByCategory(to_candid_Category_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByCity(arg0: City): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByCity(to_candid_City_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByCity(to_candid_City_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoviesByGenre(arg0: MovieGenre): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoviesByGenre(to_candid_MovieGenre_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoviesByGenre(to_candid_MovieGenre_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoviesByLanguage(arg0: Language): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoviesByLanguage(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoviesByLanguage(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<BookingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return result;
        }
    }
    async getSongsByGenre(arg0: SongGenre): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByGenre(to_candid_SongGenre_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByGenre(to_candid_SongGenre_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserRegistered(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserRegistered(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerForEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchMovies(arg0: string): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMovies(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMovies(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchSongs(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSongs(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSongs(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_City_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _City): City {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MovieGenre_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovieGenre): MovieGenre {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Movie_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Movie): Movie {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SongGenre_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SongGenre): SongGenre {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Song_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Song {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    chiefGuestName: [] | [string];
    venue: string;
    city: _City;
    date: string;
    description: string;
    organizerName: string;
    category: _Category;
    rewardEarned: bigint;
}): {
    id: bigint;
    title: string;
    creator: Principal;
    chiefGuestName?: string;
    venue: string;
    city: City;
    date: string;
    description: string;
    organizerName: string;
    category: Category;
    rewardEarned: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        chiefGuestName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.chiefGuestName)),
        venue: value.venue,
        city: from_candid_City_n18(_uploadFile, _downloadFile, value.city),
        date: value.date,
        description: value.description,
        organizerName: value.organizerName,
        category: from_candid_Category_n20(_uploadFile, _downloadFile, value.category),
        rewardEarned: value.rewardEarned
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    cast: string;
    description: string;
    director: string;
    language: _Language;
    genre: _MovieGenre;
    rating: bigint;
    releaseYear: bigint;
}): {
    id: bigint;
    title: string;
    cast: string;
    description: string;
    director: string;
    language: Language;
    genre: MovieGenre;
    rating: bigint;
    releaseYear: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        cast: value.cast,
        description: value.description,
        director: value.director,
        language: from_candid_Language_n25(_uploadFile, _downloadFile, value.language),
        genre: from_candid_MovieGenre_n27(_uploadFile, _downloadFile, value.genre),
        rating: value.rating,
        releaseYear: value.releaseYear
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    duration: string;
    language: string;
    genre: _SongGenre;
    artist: string;
}): {
    id: bigint;
    title: string;
    duration: string;
    language: string;
    genre: SongGenre;
    artist: string;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        language: value.language,
        genre: from_candid_SongGenre_n32(_uploadFile, _downloadFile, value.genre),
        artist: value.artist
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chennai: null;
} | {
    kerala: null;
} | {
    hyderabad: null;
} | {
    tamilNadu: null;
} | {
    bangalore: null;
} | {
    kochi: null;
}): City {
    return "chennai" in value ? City.chennai : "kerala" in value ? City.kerala : "hyderabad" in value ? City.hyderabad : "tamilNadu" in value ? City.tamilNadu : "bangalore" in value ? City.bangalore : "kochi" in value ? City.kochi : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collegeEvent: null;
} | {
    businessMeeting: null;
} | {
    celebrityChiefGuest: null;
}): Category {
    return "collegeEvent" in value ? Category.collegeEvent : "businessMeeting" in value ? Category.businessMeeting : "celebrityChiefGuest" in value ? Category.celebrityChiefGuest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tamil: null;
} | {
    hindi: null;
} | {
    malayalam: null;
} | {
    kannada: null;
} | {
    telugu: null;
}): Language {
    return "tamil" in value ? Language.tamil : "hindi" in value ? Language.hindi : "malayalam" in value ? Language.malayalam : "kannada" in value ? Language.kannada : "telugu" in value ? Language.telugu : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: null;
} | {
    thriller: null;
} | {
    comedy: null;
} | {
    horror: null;
} | {
    devotional: null;
} | {
    drama: null;
} | {
    romance: null;
} | {
    family: null;
}): MovieGenre {
    return "action" in value ? MovieGenre.action : "thriller" in value ? MovieGenre.thriller : "comedy" in value ? MovieGenre.comedy : "horror" in value ? MovieGenre.horror : "devotional" in value ? MovieGenre.devotional : "drama" in value ? MovieGenre.drama : "romance" in value ? MovieGenre.romance : "family" in value ? MovieGenre.family : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pop: null;
} | {
    tamil: null;
} | {
    carnatic: null;
} | {
    bollywood: null;
} | {
    folk: null;
} | {
    rock: null;
} | {
    malayalam: null;
} | {
    telugu: null;
} | {
    devotional: null;
} | {
    classical: null;
}): SongGenre {
    return "pop" in value ? SongGenre.pop : "tamil" in value ? SongGenre.tamil : "carnatic" in value ? SongGenre.carnatic : "bollywood" in value ? SongGenre.bollywood : "folk" in value ? SongGenre.folk : "rock" in value ? SongGenre.rock : "malayalam" in value ? SongGenre.malayalam : "telugu" in value ? SongGenre.telugu : "devotional" in value ? SongGenre.devotional : "classical" in value ? SongGenre.classical : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Movie>): Array<Movie> {
    return value.map((x)=>from_candid_Movie_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Array<Song> {
    return value.map((x)=>from_candid_Song_n30(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_City_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: City): _City {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MovieGenre_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovieGenre): _MovieGenre {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SongGenre_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongGenre): _SongGenre {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: City): {
    chennai: null;
} | {
    kerala: null;
} | {
    hyderabad: null;
} | {
    tamilNadu: null;
} | {
    bangalore: null;
} | {
    kochi: null;
} {
    return value == City.chennai ? {
        chennai: null
    } : value == City.kerala ? {
        kerala: null
    } : value == City.hyderabad ? {
        hyderabad: null
    } : value == City.tamilNadu ? {
        tamilNadu: null
    } : value == City.bangalore ? {
        bangalore: null
    } : value == City.kochi ? {
        kochi: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    collegeEvent: null;
} | {
    businessMeeting: null;
} | {
    celebrityChiefGuest: null;
} {
    return value == Category.collegeEvent ? {
        collegeEvent: null
    } : value == Category.businessMeeting ? {
        businessMeeting: null
    } : value == Category.celebrityChiefGuest ? {
        celebrityChiefGuest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    tamil: null;
} | {
    hindi: null;
} | {
    malayalam: null;
} | {
    kannada: null;
} | {
    telugu: null;
} {
    return value == Language.tamil ? {
        tamil: null
    } : value == Language.hindi ? {
        hindi: null
    } : value == Language.malayalam ? {
        malayalam: null
    } : value == Language.kannada ? {
        kannada: null
    } : value == Language.telugu ? {
        telugu: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovieGenre): {
    action: null;
} | {
    thriller: null;
} | {
    comedy: null;
} | {
    horror: null;
} | {
    devotional: null;
} | {
    drama: null;
} | {
    romance: null;
} | {
    family: null;
} {
    return value == MovieGenre.action ? {
        action: null
    } : value == MovieGenre.thriller ? {
        thriller: null
    } : value == MovieGenre.comedy ? {
        comedy: null
    } : value == MovieGenre.horror ? {
        horror: null
    } : value == MovieGenre.devotional ? {
        devotional: null
    } : value == MovieGenre.drama ? {
        drama: null
    } : value == MovieGenre.romance ? {
        romance: null
    } : value == MovieGenre.family ? {
        family: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongGenre): {
    pop: null;
} | {
    tamil: null;
} | {
    carnatic: null;
} | {
    bollywood: null;
} | {
    folk: null;
} | {
    rock: null;
} | {
    malayalam: null;
} | {
    telugu: null;
} | {
    devotional: null;
} | {
    classical: null;
} {
    return value == SongGenre.pop ? {
        pop: null
    } : value == SongGenre.tamil ? {
        tamil: null
    } : value == SongGenre.carnatic ? {
        carnatic: null
    } : value == SongGenre.bollywood ? {
        bollywood: null
    } : value == SongGenre.folk ? {
        folk: null
    } : value == SongGenre.rock ? {
        rock: null
    } : value == SongGenre.malayalam ? {
        malayalam: null
    } : value == SongGenre.telugu ? {
        telugu: null
    } : value == SongGenre.devotional ? {
        devotional: null
    } : value == SongGenre.classical ? {
        classical: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
